codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: down
  range: "70...95"
  
  status:
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 75%
        threshold: 5%

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false

ignore:
  - "samples/**/*"
  - "test-install/**/*"
  - "tests/**/*"
  - "**/*.Designer.cs"
  - "**/AssemblyInfo.cs"